version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kitchzero}
      POSTGRES_USER: ${POSTGRES_USER:-kitchzero}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kitchzero123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-kitchzero}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: